name: oloid2
description: ade, tomuss email pour lyon1

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  date_picker_timeline: ^1.2.3
  calendar_timeline: ^1.0.4
  dartus:
    git: https://github.com/clementherve/dartus-tomuss-client
#  bottom_sflheet: ^3.0.0
  modal_bottom_sheet: ^2.0.1
  mobile_scanner: ^2.0.0
  permission_handler: ^10.0.0
  flutter_bloc: ^8.0.0
  hive_flutter: ^1.1.0
  sizer: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  build_runner: ^2.2.0
  hive_generator: ^1.1.3

flutter:
  uses-material-design: true
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
